### ISSUE TITLE
Tabellen Prefix? Namenkürzel

### ISSUE THREAD

**Issue by Sysix** [RexDude/global_settings#1]
Für die Metainfo Intergration müssen die Tabellen Key's mit einen Prefix angegeben werden.

Hier wäre ein passender Kürzel empfehlenswert :)
Ich hab schon an was ähnliches gedacht wie **glob_**

Gruß Sysix

**Comment by RexDude** [comment]
Yo, passt für mich :)

**Comment by polarpixel** [comment]
Hi, ich verfolge gespannt die Entwicklung und werde gern testen und ggf. Ideen / Anregungen aus der Praxis beisteuern, falls gewünscht. Lg, Peter.

**Comment by RexDude** [comment]
@polarpixel  coool :)

@Sysix-Coding ich wollte heute noch 2 pages anlegen...für die sql felder und dann die Ansicht für den Redakteuer

**Comment by Sysix-Coding** [comment]
ich bin gerade dabei die metainfo intergration aufzubaun und dessen Seite. 
Kanns gegen 19 Uhr hochpushen :) liegt noch alles lokal bei mir daheim ab.

**Comment by RexDude** [comment]
oki. dann mach ich erstmal nix ;)

**Comment by Sysix-Coding** [comment]
hat ein bisschen länger gedauert als erwartet :)
Es müssen noch automatisch Spalten angelegt werden mit der entsprechenden Clang, damit man alles befüllen können.

Gruß Sysix

**Comment by RexDude** [comment]
Vielen Dank schon mal!
Uninstall ging nicht, hab ich grad gefixt.
Feld hinzufügen ging bei mir auch nicht, deshalb notices beseitig und jetzt gehts wieder.
Kannst du die notices bei dir einschalten @Sysix-Coding?

**Comment by Sysix-Coding** [comment]
Uh, hab ich vergessen einzuschalten :)

**Comment by RexDude** [comment]
Ist ja auch erledigt, _glob passt doch super :)
