### ISSUE TITLE
Checkbox geht nicht

### ISSUE THREAD

**Issue by RexDude** [RexDude/global_settings#10]
Checkbox Feld angelegt.

Zuerst kommt Notice:
Notice: Uninitialized string offset: 0 in /home/dude/Projekte/Web/p/htdocs/redaxo/include/addons/global_settings/classes/class.rex_global_settings_form.php on line 213

Dann wird der Wert nicht übernmmen. @Sysix noch dabei? kannst dir das mal anschauen?

**Comment by Sysix** [comment]
schau ich am wochenden drauf. 
Kannst du vielleicht schon sagen wie der name der Checkbox heißt? mit eckligen Klammern oder ohne?

Gruß Sysix

**Comment by RexDude** [comment]
Ok Danke!

Spaltenname: foo
Feldbezeichnung: foo
Feldtyp: checkbox

Parameter habe ich keine vergeben. Oder ist das was bei Checkbox nötig?

**Comment by Sysix** [comment]
Nein ist es nicht. Hab gerade beim alten Meta-Info Addon nachgeschaut. Da ist genau in der Zeile kein Index angegeben o.O Auch die Code Strukur sieht anders aus. Letzte Änderungen waren aber vor 2015

**Comment by RexDude** [comment]
d.h.?

**Comment by Sysix** [comment]
Irgendwie ist irgendwo was schief geloffen.
Ich hab alten Code verwendet und der war wie man hier sieht fehlerhaft. Ein kleines Update wird das sicherlich beheben

**Comment by RexDude** [comment]
Okey, danke dir.

**Comment by RexDude** [comment]
Wie schautsaus @Sysix ?
Möchte ein release raushauen.

**Comment by Sysix** [comment]
hau gleich ein commit ;) bitte dann kurz testen. hab zurzeit kein redaxo instanz lokal

**Comment by RexDude** [comment]
ja sehr gern!

**Comment by Sysix** [comment]
https://github.com/RexDude/global_settings/commit/c9ee6ed136badcef4c5cbe0927f880d256228954

**Comment by RexDude** [comment]
Läuft opitmal. Bist der Held! 
Dankeschöööön :)
