### ISSUE TITLE
Ins MetaInfo Addon einhängen?

### ISSUE THREAD

**Issue by RexDude** [RexDude/global_settings#14]
@Sysix Sag mal.....würde man dass hinbekommen die Felder Seite in das MetaInfo Addon zu hängen. Also Artikel | Katageorien, Medien | Global oder so.
Und dann sobald es ein erstes Feld gibt die Anzeige von Einstellungen/Eigenschaften direkt im Hauptmenü unter System.

Nur so ne Idee :)

**Comment by RexDude** [comment]
@Sysix Alex bitte um kurze Info. Kann man deinen Code sonst auch ins Metainfo Addon bringen als Patch...also Metainfo Addon forken underweitern um 4. Punkt: Website?

**Comment by Sysix** [comment]
ich weiß nicht mehr genau. Ich glaub das ging nicht. Redaxo hat mit rex_be_page eine Möglichkeit erstellt, diese aber fürs MetaInfo noch nicht übernommen.

Den Code vom Metainfo müsste man also teilweise umschreiben ;)

**Comment by RexDude** [comment]
> ich weiß nicht mehr genau. Ich glaub das ging nicht. Redaxo hat mit rex_be_page eine Möglichkeit erstellt, diese aber fürs MetaInfo noch nicht übernommen.

bei nem fork könnte man die möglichkeit "aktivieren" ;)

> Den Code vom Metainfo müsste man also teilweise umschreiben ;)

zfällig bock mich hier zu unterstützen? 

die idee wäre: 4. Reiter und dann so wie im Addon die Felder Page. Und dann sobald ein Feld da ist vermutlich unter System im Hauptmenü "Eigenschaften" einblenden was jetzt im Addon die Einstellungen sind. Dann noch ne Readme dazu mit der API und ferttig :)

Zufällig Bock drauf?

**Comment by Sysix** [comment]
soll das für redaxo oder pmsOne erweitert werden?

**Comment by RexDude** [comment]
ich brauche es dann für cms one. im core landets eh nicht mehr in R4. Deshalb will ich ja auch den Fork machen u.a.. Aber wers für R4 braucht kann sich auch bedienen antürlich ;)

**Comment by Sysix** [comment]
ne ist gut so :) hab ja schon vor lange zeit auf genau das Problem hingewiesen (du warst glaub icha auch dran beteiligt), aber viel gemacht wurde ja nicht.
Würd mich auch ransetzten und den Code allgemein erweiter, damit das Addon `global_settings` ausgededünnt werden kann.

Muss nur die Zeit dazu finden ;)

**Comment by RexDude** [comment]
> hab ja schon vor lange zeit auf genau das Problem hingewiesen (du warst glaub icha auch dran beteiligt), aber viel gemacht wurde ja nicht.

yup erinnere mich ;)

> Würd mich auch ransetzten und den Code allgemein erweiter, damit das Addon global_settings ausgededünnt werden kann.

Bei der Idee die ich habe wird dass überflüssig werden eigentlich.

> Muss nur die Zeit dazu finden ;)

Wo ein wille ist ist auch ein weg :)
Würde mich freuen wenn du mich hier unterstützt. Gerne dann in der CMS One Repo wenn ich alles soweit vorbereitet habe. Können ja auch n Abend dran coden zusammen (remote quasi) :)

**Comment by RexDude** [comment]
Ok alles weitere dann (hoffentlich) auf der anderen Seite.
Ich hau dich nochmal an wenns soweit is ;)

**Comment by RexDude** [comment]
@Sysix 
Das Projekt ist am Start: https://github.com/cmsone/cmsone/tree/master/redaxo/include/addons/metainfo
Falls du Bock hast zieh dir einen Fork und tob dich am Metainfo Addon aus (am besten so wie ich 
es weiter oben beschrieben habe ;))
Falls ich nix von dir höre die nächste Zeit kann es passieren das ich noch ein paar mal nerve bis ich dann aufgebe..nur so als Vorwarnung ;)

Es wäre voll cool wenn man die Funktionalität im Core hätte und dass Addon nicht mehr bräuchte :) Du kannst auch das was schon da ist rübernehmen, einen EP in den Core packen und so reingehen wenn das einfacher ist....ist mir alles recht :)

Cheers!
