### ISSUE TITLE
Shortcodes / Platzhalter

### ISSUE THREAD

**Issue by alexplusde** [RexDude/global_settings#17]
Interessant wäre es, wenn man die Werte auch direkt ausgeben kann, bspw. REX_GLOBAL[field="name"]

**Comment by RexDude** [comment]
Hmm für mich persönlich uninteressant. Ich nutze am liebsten die PHP Methoden :) Wenn du es aber unbedingt brauchst und dich einbringen willst inkl. tests und support etc. sag bescheid ;)

**Comment by alexplusde** [comment]
Hab verstanden ;)
