### ISSUE TITLE
Nutzung im Backend

### ISSUE THREAD

**Issue by phoebusryan** [RexDude/global_settings#18]
Mir ist gerade aufgefallen, dass wenn ich das Addon im Backend nutze (z.b. in der boot.php des Projekt-Addons), ich lediglich einen fehler "Call to a member function reset() on null" erhalte. Wäre es aufwendig dies zu fixen?

**Comment by RexDude** [comment]
Ich vermute mal es liegt daran dass der init erst bei PACKAGES_INCLUDED passiert, siehe https://github.com/RexDude/global_settings/blob/master/boot.php#L30.
Daher solltest du deinen Aufruf im Backend auch so machen in deinem Addon.
Ändern würd ich dass hier nur ungern weil a) weiss ich gar nicht mehr warum genau ich dass so gemacht habe :) (oder obs aus dem Metainfo Addon übernommen wurde) und b) wird man so oder so ein Problem bekommen falls ein Addon früher geladen wird (z.b. wenns dessen Name mit f oder geringer beginnt :P).

**Comment by RexDude** [comment]
Aber ne Exception werfen sollte ich hier aufjedefall...

**Comment by phoebusryan** [comment]
Ah, über PACKAGES_INCLUDED klappt es. Danke für den Tipp.
