### ISSUE TITLE
Mehrsprachigkeit

### ISSUE THREAD

**Issue by Sysix** [RexDude/global_settings#2]
Hallo,

soll auch die Mehrsprachigkeit berücksichtig werden?

Gruß Sysix

**Comment by RexDude** [comment]
Wäre cool ja. Allerdings müsste man das mal genauer durchdenken, weil z.B. wenn man ein Logo ablegt dann braucht man das ja meist nicht mehrsprachig.

@polarpixel Was meinst du?

**Comment by polarpixel** [comment]
Mehrsprachigkeit: unbedingt! Aber RexDude hat recht, dass man es nicht bei allen Feldern braucht. Neben Logo fallen mir z.B. Links zu Social Networks ein, die man in einem so einem AddOn speichern möchte.
Perfekt wäre, wenn man für jedes Feld speichern könnte, ob es mehrsprachig sein soll oder nicht.
Oder man geht es technisch so an, dass es zwei Sektionen gibt: mehrsprachige Felder und nur einsprachige Felder. (vielleicht sogar zwei verschiedene DB-Tabellen?)

**Comment by Sysix-Coding** [comment]
Auf die Idee es komplett zu trennen, bin ich noch nicht gekommen :)

Solch eine Einstellung muss für jedes Feld speziell gewählt werden.
Daher würde ich vorschlagen:
- direkt bei der Feld-Erstellung (Metainfo)
- Radio-Switcher (hab sowieso Bock drauf das mit Ajax zu machn :santa:)

Gruß Sysix

**Comment by RexDude** [comment]
Da Mehrsprachigkeit drin ist brauchts erstmal nix weiter.
Man kann über die API auch immer nur die Values einer Sprache holen egal in welcher Sprache man ist.
