### ISSUE TITLE
rex_sql_exception beim Löschen von Dateien im Mediapool wegen Global Settings Variable

### ISSUE THREAD

**Issue by omphteliba** [RexDude/global_settings#20]
Wenn ich ersuche eine Datei im Mediapool zu löschen bekomme ich folgende Exception:

`rex_sql_exception Error while executing statement "SELECT id, clang_id, parent_id, name, catname, startarticle FROM rex_article WHEREart_file= 'cx_seminare_2018.pdf' ORasd_picture= 'cx_seminare_2018.pdf' ORart_llp_hover= 'cx_seminare_2018.pdf' ORart_llp_vorschau_uebersicht= 'cx_seminare_2018.pdf' ORart_og_image= 'cx_seminare_2018.pdf' ORasd_jobimage= 'cx_seminare_2018.pdf' ORasd_jobhover= 'cx_seminare_2018.pdf' OR FIND_IN_SET('cx_seminare_2018.pdf',glob_footer_logos)"! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'glob_footer_logos' in 'where clause'`

Ich habe ein Feld "footer_logos" in Global Settings eingetragen.

![image](https://user-images.githubusercontent.com/196336/36199156-f758b216-1178-11e8-9d36-ea856ea900f3.png)

**Comment by RexDude** [comment]
Kannst du gar keine Dateien mehr löschen oder nur die cx_seminare_2018.pdf?

**Comment by omphteliba** [comment]
Ich kann gar keine Dateien mehr löschen. cx_seminare_2018.pdf war nur ein Beispiel.

**Comment by RexDude** [comment]
Hmm kann mir noch nicht wirklich erklären was da passiert ist.
Kannst du dass irgendwie auf einer frischen testinstallation reproduzieren und mir dann die Schritte mitteilen?
Btw: für dich mal um Dateien wieder löschen zu können: lege ein varchar Feld 'glob_footer_logos' in der rex_article Tabelle an.
(ungetestet ;))

**Comment by omphteliba** [comment]
Also müsste jedes Feld das ich im Addon "Globale Settings" angelegt habe, als Feld in der Tabelle rex_article erscheinen?

**Comment by RexDude** [comment]
Nein eben nicht. Das Addon hat seine eigene Tabelle wo die glob_ Felder drin landen. Aber REDAXO sucht dass bei dir in der rex_article und deshalb wenn du es dort mal anlegst kannst du zumindest wieder Dateien löschen.

**Comment by RexDude** [comment]
Ist aber kein Fix sonder nur ein Workaround.

**Comment by omphteliba** [comment]
Weil ich habe noch ein weiteres "glob_" Feld in der rex_article Tabelle. 
Aber zumindest ist das Problem behoben. 

Ich hatte das Issue zuerst bei Redaxo aufgemacht, ich wurde dann aber hierher verwiesen. Sollte ich das da nochmal anstoßen?

**Comment by RexDude** [comment]
Ne vermutlich kommt schon eher von Adoon ;)
Aber hab aktuell keine Erklärung was da bei dir passiert ist.

**Comment by staabm** [comment]
alternativ könnte ich mir eine kombination aus dump via backup addon eingespielt und addon re-installiert o.ä. ganz gut vorstellen

**Comment by staabm** [comment]
metainfo muss z.b. hier eine cleanup-routine starten
https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/metainfo/uninstall.php

**Comment by DanielWeitenauer** [comment]
Moin,

ich nehme an, das Problem kommt dadurch zustande, dass das Metainfo-Addon beim Usage-Check nur die drei Core-Tabellen berücksichtigt: https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/metainfo/lib/handler/media_handler.php#L43-L49
rex_article ist dadurch dann quasi die Fallback-tabelle, wenn der Prefix nicht erkannt wird.

**Comment by RexDude** [comment]
ok danke euch. und was heisst das jetzt konkret? :)

**Comment by DanielWeitenauer** [comment]
Langfristig sollte MetaInfo-Addon eine Möglichkeit eingebaut werden eigene Tabellen einzufügen. Kurzfristig könnte man im MetaInfo-Addon die Prüfung überspringen, wenn der Prefix nicht erkannt wird. Aber wahrscheinlich muss die Änderung dort stattfinden.

**Comment by Sysix** [comment]
@DanielWeitenauer wir benuthzen den `media_handler` von Redaxo nicht. Wir haben dafür einen eigenen Handler geschrieben:  
https://github.com/RexDude/global_settings/blob/master/lib/handler/global_settings_handler.php

Jemand müsste mal drauf schauen, ob sich währenddessen am MetaInfo-AddOn was verändert hat.  
Das müsste man wieder im AddOn nachziehen.   

Aber natürlich wäre eine Schnittstelle seitens MetaInfo-AddOn besser :)

**Comment by DanielWeitenauer** [comment]
@Sysix Das Metainfo-Addon het einen media_handler für die Core-Tabellen. Der wird immer aufgerufen und wenn er den Prefix nicht erkennt, sucht er in rex_article, dadurch gibt es einen Fehler. Habe ich doch oben verlinkt. Euer Addon hat also nichts damit zu tun, ist ein Core-Problem.

**Comment by RexDude** [comment]
Danke an alle insbesondere @DanielWeitenauer für das finale Statement :)
