### ISSUE TITLE
Seite Einstellungen und "Eigenschaften" sollten getrennt werden

### ISSUE THREAD

**Issue by RexDude** [RexDude/global_settings#3]
Die ursprüngliche Seite Einstellungen ist lediglich für die Addon Einstellungen gedacht, wenn es überhaupt welche gibt. Ich würde noch ne 2 Seite "Eigenschaften" machen für die MetaInfoFelder. 

Desweiteren kommt "Fehler beim speichern!" aktuell auf der Seite bei mir. 

Wegen Namensgebnung müssen wir vielleicht nochmal uns alle zusammentun, bzw. ich Brainstorme mal mit @polarpixel darüber.

**Comment by polarpixel** [comment]
"Fehler beim Speichern" auch bei mir.

Zur Benennung:
Die Einstellungen des AddOns vielleicht AddOn-Einstellungen nennen? Diese Seite sollte m.E. nur der Admin sehen können.

Die Felder für den Redakteur sollten idealerweise auf mehrere Untermenüs aufgeteilt werden können, ich weiß nicht, ob das geplant ist. So hätte der Redakteur z.B. einen Untermenüpunkt "Footer", einen "Social Links", etc. Wobei ja die Mehrsprachigkeit auch noch dazu kommt, hm ...

Wenn's nicht anders geht, kann man natürlich auch mit nur einer Seite Fieldsets arbeiten, aber wie gesagt: Mehrere Seiten wären schick ...

**Comment by RexDude** [comment]
Hmm mehrere Seite wirds alles noch bisschen schwieriger. Evtl. für ne nächste Version? Fieldset ist doch aber auch völlig ausreichend....ich meine soi viele tauend Punkte für einen Footer wird auch nicht geben. Du kannst dazu aber ein Issuu auf machen.

**Comment by polarpixel** [comment]
Ist halt einfach eine Möglichkeit, um das noch besser zu strukturieren, statt eine lange Seite zu haben.
Ist nicht so wichtig, ich lass das mit dem Issue erst mal. Vielleicht optional ein Akkordeon für die Fieldsets anbieten? Das wäre technisch vermutlich nicht so schwierig, oder?

Wenn es nur eine Seite gibt, würde ich die "Website-Einstellungen" oder "Globale Einstellungen" nennen.

**Comment by Sysix-Coding** [comment]
ich hab den Speichern-Bug behoben.

zum Thema:

**Fieldssets**
lassen sich schon automatisch über Metainfo erweitern
**Akkordeon**
wird etwas komplizierter, da die Formulargenerierung komplett das Metainfo Addon übernimmt.
**Einzelne Seiten**
Ist eine Nette Idee. Wir bräuchten nur einen Controller der abfrägt, auf welcher Seite welche Felder angezeigt werden sollen. Dieser müsste sich automatisch erweitern/schmälern.

Ich würde aber dafür lieber Tabs als Seiten benutzen :)

**Comment by polarpixel** [comment]
Tabs (Du meinst ja sicher Javascript-Tabs) wären ebenso gut oder vielleicht noch besser. Wobei, ist das vom Umsetzungsprinzip nicht ebenso wie Akkordeons?

**Comment by RexDude** [comment]
Man könnte aber auch sowas wie bei "Hilfe" machen die Chapters. Vorteil: Es braucht kein JS.

**Comment by RexDude** [comment]
Da es keine Addon-Einstellungen gibt z.Z. hat sich das erstmal erledigt mit der Aufteilung.
