### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by polarpixel** [RexDude/global_settings#5]
Sagt mal, wahrscheinlich ne total blöde Frage, aber wie erfolgt die Ausgabe der Werte im Frontend? Wollte mal damit rumspielen ... oder ist das noch nicht fertig?

**Comment by Sysix-Coding** [comment]
Die Ausgabe ist noch nicht entwickelt. 
Aber an sich wird es eine SQL Abfrage mit der clang Abfrage.
Die einzelne Felder kann man mit den Prefix glob_ erreichen.
Das ganze in einer schönen Klasse und dann schon fertig :)

**Comment by polarpixel** [comment]
Ok, alles klar und Danke.
