### ISSUE TITLE
Bug in Redaxo 4.6.2 und PHP 5.3

### ISSUE THREAD

**Issue by godsdog** [RexDude/global_settings#8]
Hallo wenn man mit PHP 5.3 und Redaxo 4.6.2 Felder befüllen möchte, werden diese auch korrekt in die DB geschrieben, jedoch nicht korrekt ausgelesen. Es erscheint lediglich ein UNIX Timestamp als Value im Feld.

**Comment by Sysix** [comment]
Der Fehler ist der gleiche wie hier: https://github.com/Sysix/asd_news/issues/28

**Comment by polarpixel** [comment]
Ich kann das Problem bestätigen.
PHP 5.3.3-7 und Redaxo 4.6.1, MySQL 5.1

Im Frontend ist die Ausgabe aber korrekt, nur in Redaxo sind die Zahlen in den Feldern zu sehen.

**Comment by RexDude** [comment]
@godsdog 
@polarpixel 
Bug wurde gefixt. Bitte mal testen.

**Comment by polarpixel** [comment]
Klappt jetzt.
Danke!
